// src/components/MovieRecommendations.jsx
// MovieRecommendations.jsx
import React from "react";
import data from "../data/data.json";

const currentDate = new Date().toISOString().split("T")[0]; // Get current date in "YYYY-MM-DD" format

const MovieRecommendations = () => {
  const filteredEvents = data.commemorativeEvents.filter(
    (event) => event.date === currentDate
  );

  return (
    <div className="movie-recommendations">
      {filteredEvents.map((event) => (
        <div key={event.id} className="event-section">
          <h3>{event.name}</h3>
          <div className="movie-list">
            {event.movies.map((movie) => (
              <div key={movie.id} className="movie-item">
                <img src={movie.poster} alt={movie.title} />
                <div className="movie-details">
                  <h4>{movie.title}</h4>
                  <p>{movie.portugueseTitle}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
};

export default MovieRecommendations;

// src/components/MovieRecommendations/MovieRecommendations.vue
<template>
  <div :class="$style.movieRecommendations">
    <div v-for="(movies, eventDate) in movieSuggestions" :key="eventDate">
      <h2>{{ eventDate }} Movie Recommendations:</h2>
      <div :class="$style.movieList">
        <div v-for="movie in movies" :key="movie.id" :class="$style.movie">
          <img :src="movie.poster" alt="Movie Poster" />
          <h3>{{ movie.title }}</h3>
          <p>{{ movie.description }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import styles from "./MovieRecommendations.module.scss";

export default defineComponent({
  data() {
    return {
      movieSuggestions: {},
    };
  },
});
</script>

<style module lang="scss">
@import "./MovieRecommendations.module.scss";
</style>
